abstract class ConfirmaMapScreenStates{}

class InitialConfirmaMapScreenStates extends ConfirmaMapScreenStates{}

class ChangePositionLocationConfirmaMapScreen extends ConfirmaMapScreenStates{}

class PolylineState extends ConfirmaMapScreenStates{}

class GoToMyCurrentLocationConfirmaMapScreenState extends ConfirmaMapScreenStates{}

class AddCurrentMarkerSetConfirmaMapScreenState extends ConfirmaMapScreenStates{}

class SetCustomMarkerConfirmaMapScreenState extends ConfirmaMapScreenStates{}

class AddTapMarkerToSet extends ConfirmaMapScreenStates{}

